package generator

import (
	"fmt"
	"strings"

	"github.com/wahyunoerr/go-boost/pkg/astparser"
)

func GenerateMockCode(rootDir string, interfaceName string) (string, error) {
	symbols, err := astparser.ParsePath(rootDir)
	if err != nil {
		return "", fmt.Errorf("failed to parse AST: %w", err)
	}

	var targetInterface *astparser.InterfaceInfo
	for i := range symbols.Interfaces {
		if strings.EqualFold(symbols.Interfaces[i].Name, interfaceName) {
			targetInterface = &symbols.Interfaces[i]
			break
		}
	}

	if targetInterface == nil {
		return "", fmt.Errorf("interface '%s' not found in project", interfaceName)
	}

	mockStructName := "Mock" + targetInterface.Name
	var sb strings.Builder

	neededImports := map[string]bool{"sync": true}
	for _, m := range targetInterface.Methods {
		for _, p := range m.Params {
			if strings.Contains(p, "context.Context") {
				neededImports["context"] = true
			}
			if strings.Contains(p, "time.Time") || strings.Contains(p, "time.Duration") {
				neededImports["time"] = true
			}
			if strings.Contains(p, "io.Reader") || strings.Contains(p, "io.Writer") || strings.Contains(p, "io.Closer") {
				neededImports["io"] = true
			}
			if strings.Contains(p, "http.Request") || strings.Contains(p, "http.ResponseWriter") {
				neededImports["net/http"] = true
			}
		}
		for _, r := range m.Returns {
			if strings.Contains(r, "context.Context") {
				neededImports["context"] = true
			}
			if strings.Contains(r, "time.Time") || strings.Contains(r, "time.Duration") {
				neededImports["time"] = true
			}
			if strings.Contains(r, "io.Reader") || strings.Contains(r, "io.Writer") || strings.Contains(r, "io.Closer") {
				neededImports["io"] = true
			}
			if strings.Contains(r, "http.Request") || strings.Contains(r, "http.ResponseWriter") {
				neededImports["net/http"] = true
			}
		}
	}

	pkgName := symbols.Package
	if pkgName == "" {
		pkgName = "mocks"
	}

	sb.WriteString("// Code generated by go-boost; DO NOT EDIT.\n\n")
	sb.WriteString("package " + pkgName + "\n\n")
	sb.WriteString("import (\n")
	for imp := range neededImports {
		sb.WriteString(fmt.Sprintf("\t\"%s\"\n", imp))
	}
	sb.WriteString(")\n\n")

	sb.WriteString(fmt.Sprintf("type %s struct {\n", mockStructName))
	sb.WriteString("\tmu sync.Mutex\n")
	sb.WriteString("\tCalls map[string]int\n")

	for _, m := range targetInterface.Methods {
		fnType := formatFuncType(m.Params, m.Returns)
		sb.WriteString(fmt.Sprintf("\t%sFunc %s\n", m.Name, fnType))
	}
	sb.WriteString("}\n\n")

	sb.WriteString(fmt.Sprintf("func New%s() *%s {\n", mockStructName, mockStructName))
	sb.WriteString(fmt.Sprintf("\treturn &%s{\n", mockStructName))
	sb.WriteString("\t\tCalls: make(map[string]int),\n")
	sb.WriteString("\t}\n")
	sb.WriteString("}\n\n")

	for _, m := range targetInterface.Methods {
		paramNames := make([]string, 0, len(m.Params))
		for i, p := range m.Params {
			parts := strings.Fields(p)
			if len(parts) >= 2 {
				paramNames = append(paramNames, parts[0])
			} else {
				paramNames = append(paramNames, fmt.Sprintf("arg%d", i))
			}
		}

		sigParams := strings.Join(m.Params, ", ")
		callParams := strings.Join(paramNames, ", ")
		returnTypes := strings.Join(m.Returns, ", ")
		if len(m.Returns) > 1 {
			returnTypes = "(" + returnTypes + ")"
		}

		returnStmt := ""
		if len(m.Returns) > 0 {
			returnStmt = "return "
		}

		sb.WriteString(fmt.Sprintf("func (m *%s) %s(%s) %s {\n", mockStructName, m.Name, sigParams, returnTypes))
		sb.WriteString("\tm.mu.Lock()\n")
		sb.WriteString(fmt.Sprintf("\tm.Calls[\"%s\"]++\n", m.Name))
		sb.WriteString("\tm.mu.Unlock()\n\n")
		sb.WriteString(fmt.Sprintf("\tif m.%sFunc != nil {\n", m.Name))
		sb.WriteString(fmt.Sprintf("\t\t%sm.%sFunc(%s)\n", returnStmt, m.Name, callParams))
		sb.WriteString("\t}\n")

		if len(m.Returns) > 0 {
			zeroVals := make([]string, len(m.Returns))
			for i, r := range m.Returns {
				zeroVals[i] = zeroValueForType(r)
			}
			sb.WriteString(fmt.Sprintf("\treturn %s\n", strings.Join(zeroVals, ", ")))
		}
		sb.WriteString("}\n\n")
	}

	return sb.String(), nil
}

func formatFuncType(params []string, returns []string) string {
	p := strings.Join(params, ", ")
	r := strings.Join(returns, ", ")
	if len(returns) > 1 {
		r = "(" + r + ")"
	}
	if len(returns) == 0 {
		return fmt.Sprintf("func(%s)", p)
	}
	return fmt.Sprintf("func(%s) %s", p, r)
}

func zeroValueForType(t string) string {
	clean := strings.TrimSpace(t)
	switch clean {
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "byte", "rune":
		return "0"
	case "float32", "float64":
		return "0.0"
	case "string":
		return `""`
	case "bool":
		return "false"
	case "error":
		return "nil"
	default:
		if strings.HasPrefix(clean, "*") || strings.HasPrefix(clean, "[]") || strings.HasPrefix(clean, "map[") || strings.HasPrefix(clean, "chan") || clean == "any" {
			return "nil"
		}

		return clean + "{}"
	}
}
